import { Inter } from "next/font/google";
import MainHeader from "../../components/main-header/index";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Routing & Page Rendering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="page">
          <MainHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
